<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="83039" started-at="2020-12-13T05:23:26Z" finished-at="2020-12-13T05:24:49Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="83039" started-at="2020-12-13T05:23:26Z" finished-at="2020-12-13T05:24:49Z">
      <class name="testcases.TC_Assessment">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:testcases.TC_Assessment@1c0542]" name="beforeSuite" is-config="true" duration-ms="809" started-at="2020-12-13T05:23:25Z" finished-at="2020-12-13T05:23:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:testcases.TC_Assessment@1c0542]" name="beforeClass" is-config="true" duration-ms="0" started-at="2020-12-13T05:23:26Z" finished-at="2020-12-13T05:23:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="setData()[pri:0, instance:testcases.TC_Assessment@1c0542]" name="setData" is-config="true" duration-ms="0" started-at="2020-12-13T05:23:26Z" finished-at="2020-12-13T05:23:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setData -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testcases.TC_Assessment@1c0542]" name="beforeMethod" is-config="true" duration-ms="10121" started-at="2020-12-13T05:23:26Z" finished-at="2020-12-13T05:23:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="assessmentTestCase()[pri:0, instance:testcases.TC_Assessment@1c0542]" name="assessmentTestCase" duration-ms="72887" started-at="2020-12-13T05:23:36Z" finished-at="2020-12-13T05:24:49Z">
          <exception class="java.lang.RuntimeException">
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException
at lib.utils.HTMLReporter.reportStep(HTMLReporter.java:66)
at lib.utils.HTMLReporter.reportStep(HTMLReporter.java:75)
at lib.selenium.WebDriverServiceImpl.locateElement(WebDriverServiceImpl.java:86)
at pages.ServiceConsolePage.closeFileWindowTab(ServiceConsolePage.java:99)
at testcases.TC_Assessment.assessmentTestCase(TC_Assessment.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- assessmentTestCase -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:testcases.TC_Assessment@1c0542]" name="afterMethod" is-config="true" duration-ms="0" started-at="2020-12-13T05:24:49Z" finished-at="2020-12-13T05:24:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:testcases.TC_Assessment@1c0542]" name="afterSuite" is-config="true" duration-ms="398" started-at="2020-12-13T05:24:49Z" finished-at="2020-12-13T05:24:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- testcases.TC_Assessment -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
